#pragma once

#include "../../../../JObject.hpp"

namespace android::health::connect::datatypes
{
	class ExerciseSegmentType : public JObject
	{
	public:
		// Fields
		static jint EXERCISE_SEGMENT_TYPE_ARM_CURL();
		static jint EXERCISE_SEGMENT_TYPE_BACK_EXTENSION();
		static jint EXERCISE_SEGMENT_TYPE_BALL_SLAM();
		static jint EXERCISE_SEGMENT_TYPE_BARBELL_SHOULDER_PRESS();
		static jint EXERCISE_SEGMENT_TYPE_BENCH_PRESS();
		static jint EXERCISE_SEGMENT_TYPE_BENCH_SIT_UP();
		static jint EXERCISE_SEGMENT_TYPE_BIKING();
		static jint EXERCISE_SEGMENT_TYPE_BIKING_STATIONARY();
		static jint EXERCISE_SEGMENT_TYPE_BURPEE();
		static jint EXERCISE_SEGMENT_TYPE_CRUNCH();
		static jint EXERCISE_SEGMENT_TYPE_DEADLIFT();
		static jint EXERCISE_SEGMENT_TYPE_DOUBLE_ARM_TRICEPS_EXTENSION();
		static jint EXERCISE_SEGMENT_TYPE_DUMBBELL_CURL_LEFT_ARM();
		static jint EXERCISE_SEGMENT_TYPE_DUMBBELL_CURL_RIGHT_ARM();
		static jint EXERCISE_SEGMENT_TYPE_DUMBBELL_FRONT_RAISE();
		static jint EXERCISE_SEGMENT_TYPE_DUMBBELL_LATERAL_RAISE();
		static jint EXERCISE_SEGMENT_TYPE_DUMBBELL_ROW();
		static jint EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_LEFT_ARM();
		static jint EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_RIGHT_ARM();
		static jint EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_TWO_ARM();
		static jint EXERCISE_SEGMENT_TYPE_ELLIPTICAL();
		static jint EXERCISE_SEGMENT_TYPE_FORWARD_TWIST();
		static jint EXERCISE_SEGMENT_TYPE_FRONT_RAISE();
		static jint EXERCISE_SEGMENT_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING();
		static jint EXERCISE_SEGMENT_TYPE_HIP_THRUST();
		static jint EXERCISE_SEGMENT_TYPE_HULA_HOOP();
		static jint EXERCISE_SEGMENT_TYPE_JUMPING_JACK();
		static jint EXERCISE_SEGMENT_TYPE_JUMP_ROPE();
		static jint EXERCISE_SEGMENT_TYPE_KETTLEBELL_SWING();
		static jint EXERCISE_SEGMENT_TYPE_LATERAL_RAISE();
		static jint EXERCISE_SEGMENT_TYPE_LAT_PULL_DOWN();
		static jint EXERCISE_SEGMENT_TYPE_LEG_CURL();
		static jint EXERCISE_SEGMENT_TYPE_LEG_EXTENSION();
		static jint EXERCISE_SEGMENT_TYPE_LEG_PRESS();
		static jint EXERCISE_SEGMENT_TYPE_LEG_RAISE();
		static jint EXERCISE_SEGMENT_TYPE_LUNGE();
		static jint EXERCISE_SEGMENT_TYPE_MOUNTAIN_CLIMBER();
		static jint EXERCISE_SEGMENT_TYPE_OTHER_WORKOUT();
		static jint EXERCISE_SEGMENT_TYPE_PAUSE();
		static jint EXERCISE_SEGMENT_TYPE_PILATES();
		static jint EXERCISE_SEGMENT_TYPE_PLANK();
		static jint EXERCISE_SEGMENT_TYPE_PULL_UP();
		static jint EXERCISE_SEGMENT_TYPE_PUNCH();
		static jint EXERCISE_SEGMENT_TYPE_REST();
		static jint EXERCISE_SEGMENT_TYPE_ROWING_MACHINE();
		static jint EXERCISE_SEGMENT_TYPE_RUNNING();
		static jint EXERCISE_SEGMENT_TYPE_RUNNING_TREADMILL();
		static jint EXERCISE_SEGMENT_TYPE_SHOULDER_PRESS();
		static jint EXERCISE_SEGMENT_TYPE_SINGLE_ARM_TRICEPS_EXTENSION();
		static jint EXERCISE_SEGMENT_TYPE_SIT_UP();
		static jint EXERCISE_SEGMENT_TYPE_SQUAT();
		static jint EXERCISE_SEGMENT_TYPE_STAIR_CLIMBING();
		static jint EXERCISE_SEGMENT_TYPE_STAIR_CLIMBING_MACHINE();
		static jint EXERCISE_SEGMENT_TYPE_STRETCHING();
		static jint EXERCISE_SEGMENT_TYPE_SWIMMING_BACKSTROKE();
		static jint EXERCISE_SEGMENT_TYPE_SWIMMING_BREASTSTROKE();
		static jint EXERCISE_SEGMENT_TYPE_SWIMMING_BUTTERFLY();
		static jint EXERCISE_SEGMENT_TYPE_SWIMMING_FREESTYLE();
		static jint EXERCISE_SEGMENT_TYPE_SWIMMING_MIXED();
		static jint EXERCISE_SEGMENT_TYPE_SWIMMING_OPEN_WATER();
		static jint EXERCISE_SEGMENT_TYPE_SWIMMING_OTHER();
		static jint EXERCISE_SEGMENT_TYPE_SWIMMING_POOL();
		static jint EXERCISE_SEGMENT_TYPE_UNKNOWN();
		static jint EXERCISE_SEGMENT_TYPE_UPPER_TWIST();
		static jint EXERCISE_SEGMENT_TYPE_WALKING();
		static jint EXERCISE_SEGMENT_TYPE_WEIGHTLIFTING();
		static jint EXERCISE_SEGMENT_TYPE_WHEELCHAIR();
		static jint EXERCISE_SEGMENT_TYPE_YOGA();
		
		// QJniObject forward
		template<typename ...Ts> explicit ExerciseSegmentType(const char *className, const char *sig, Ts...agv) : JObject(className, sig, std::forward<Ts>(agv)...) {}
		ExerciseSegmentType(QJniObject obj) : JObject(obj) {}
		
		// Constructors
		
		// Methods
	};
} // namespace android::health::connect::datatypes

