name: Build
on:
  release:
    types: [created]
  push:
    branches: [ Qt5Dev ]
  pull_request:
    branches: [ Qt5Dev ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    strategy:
      matrix:
        host: 
          - runs-on: ubuntu-latest
            qt-host: linux
          # - runs-on: macos-latest
          #   qt-host: mac
          # - runs-on: windows-latest
          #   qt-host: windows
        android-arch: 
          - android
          # - android_armv7
          # - android_arm64-v8a
          # - android_x86
          # - android_x86_64
        android-api-version:
          - android-28
          # - android-29
          # - android-30
          # - android-31
    runs-on: ${{ matrix.host.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r21e
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: 5.15.2
          host: ${{ matrix.host.qt-host }}
          target: android
          arch: ${{ matrix.android-arch }}
      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -S ${{ matrix.android-api-version }} -DCMAKE_BUILD_TYPE:STRING=${{ env.BUILD_TYPE }} -DANDROID_NDK:PATH=${{ steps.setup-ndk.outputs.ndk-path }} -DCMAKE_TOOLCHAIN_FILE:PATH=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}
