name: Build
on:
  release:
    types: [created]
  push:
    branches: [ Qt5Dev ]
  pull_request:
    branches: [ Qt5Dev ]
env:
  BUILD_TYPE: Release
  NDK_VERSION: r21d
  QT_VERSION: 5.15.2
jobs:
  build:
    strategy:
      matrix:
        host: 
          - runs-on: ubuntu-latest
            qt: linux
          - runs-on: macos-latest
            qt: mac
          - runs-on: windows-latest
            qt: windows
        android-arch: 
          - android
          # - android_armv7
          # - android_arm64-v8a
          # - android_x86
          # - android_x86_64
        android-api-version:
          - android-28
          # - android-29
          # - android-30
          # - android-31
    runs-on: ${{ matrix.host.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: ${{ env.QT_VERSION }}
          host: ${{ matrix.host.qt }}
          target: android
          arch: ${{ matrix.android-arch }}
      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -S ${{ matrix.android-api-version }} -DCMAKE_BUILD_TYPE:STRING=${{ env.BUILD_TYPE }} -DANDROID_NDK:PATH=${{ steps.setup-ndk.outputs.ndk-path }} -DCMAKE_TOOLCHAIN_FILE:PATH=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake -DCMAKE_FIND_ROOT_PATH:PATH=${{ env.Qt5_DIR }}
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }} -j ${{ steps.cpu-cores.outputs.count }}
