name: Build
on:
  release:
    types: [created]
  push:
    branches: [ Qt5Dev ]
  pull_request:
    branches: [ Qt5Dev ]
env:
  BUILD_TYPE: Release
jobs:
  build:
    strategy:
      matrix:
        host: 
          - name: linux
            os: ubuntu-latest
          - name: mac
            os: macos-latest
          - name: windows
            os: windows-latest
        arch: [android]
        # api: [android-28, android-29, android-30, android-31]
        api: [android-28]
    runs-on: ${{ matrix.host.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Qt
        uses: WillBrennan/yaqti@main
        with:
          version: 5.15.2
          os: ${{ matrix.host.name }}
          platform: android
          modules: android
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S ${{ matrix.api }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
