name: Test
on:
  push:
    branches: [ Qt5 ]
  pull_request:
    branches: [ Qt5 ]
env:
  BUILD_TYPE: Release
  NDK_VERSION: r21d
  QT_VERSION: 5.15.2
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - qt: android
            abi: armeabi-v7a
          - qt: android
            abi: arm64-v8a
          - qt: android
            abi: x86
          - qt: android
            abi: x86_64
        android-api-version:
          - android-28
          - android-29
          - android-30
          - android-31
          - android-32
          - android-33
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION }}
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: ../Qt
          key: ${{ runner.os }}-Qt${{ env.QT_VERSION }}-${{ matrix.arch.qt }}-Cache
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          version: ${{ env.QT_VERSION }}
          host: linux
          target: android
          arch: ${{ matrix.arch.qt }}
      - name: Configure CMake
        run: |
          cmake -B ./build -S ${{ matrix.android-api-version }} \
          -G"Unix Makefiles" \
          -DCMAKE_BUILD_TYPE:STRING=${{ env.BUILD_TYPE }} \
          -DANDROID_NDK:PATH=${{ steps.setup-ndk.outputs.ndk-path }} \
          -DCMAKE_TOOLCHAIN_FILE:PATH=${{ steps.setup-ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
          -DCMAKE_FIND_ROOT_PATH:PATH=${{ env.Qt5_DIR }} \
          -DANDROID_ABI:STRING=${{ matrix.arch.abi }} \
          -DCMAKE_INSTALL_PREFIX=./install \
          -DQT_ANDROID_API_TEST:BOOL=ON
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: Build
        run: cmake --build ./build --config ${{ env.BUILD_TYPE }} -j ${{ steps.cpu-cores.outputs.count }}
